#!/system/bin/sh
# Version: 1.0.3
# export path for android bins/tools
export PATH=/data/data/com.offsec.nethunter/files/scripts/:/data/data/com.offsec.nethunter/files/scripts/bin:/data/data/hilled.pwnterm/files/usr/bin:/data/data/hilled.pwnterm/files/usr/sbin:/sbin:/system/bin:/system/xbin:/apex/com.android.runtime/bin:/apex/com.android.art/bin:/odm/bin:/vendor/bin:.
export TMP=/tmp
export PREFIX=/

# Unset some NeoStuff
unset __NEOTERM_ORIGIN_PATH
unset __NEOTERM_ORIGIN_LD_LIBRARY_PATH

# get su path
export SU=$(which su)

$SU -c bootkali
