#!/data/data/hilled.pwnterm/files/usr/bin/bash
ROOTPATH=/data/data/hilled.pwnterm/files/usr/sbin/bootkali
if [ -f $ROOTPATH ]; then
  true
  else
    ROOTPATH=/data/data/hilled.pwnterm/files/usr/bin/bootkali
    if [ -f $ROOTPATH ]; then
      true
    else
      echo "[!]: Please install nethunter-support package from apt/pkg"
      exit
    fi
fi

# export path for android bins/tools
export TMP=/tmp
export PREFIX=/

# get su path and bootkali
export SU=$(which su)
export BK=$(which bootkali)

# unset things and readd chroot things
unset PATH
unset TMP
unset TMPDIR
unset HOME
unset LD_PRELOAD
unset __NEOTERM_ORIGIN_PATH
unset __NEOTERM_ORIGIN_LD_LIBRARY_PATH

## Combine android $PATH to kali chroot $PATH
export TERM=xterm-256color
export SHELL=/bin/bash
export LANG=en_US.UTF-8
export HOME=/root
export TMP=/tmp
export TMPDIR=/tmp
export USER=root
export MAIL=/var/mail/root
export LOGNAME=root
export SHLVL=root
# Lets pass a binky export here too ;)
export YOU_KNOW_WHAT=THIS_IS_KALI_LINUX_NETHUNTER_FROM_JAVA_BINKY

$SU -c $BK
